// English country name (as ACLED spells it) → { ar: Arabic label, iso2: ISO
// 3166-1 alpha-2 }. ACLED's `country` field is a plain English name with no
// Arabic label and no ISO code, so this is the only place that translation
// happens for the Security Threats card.
//
// A country ACLED reports that ISN'T in this map still appears in the widget
// (never dropped) — resolveCountry() returns null and the caller falls back
// to the raw ACLED name with no flag/ISO badge, rather than inventing one.

const COUNTRY_INFO = {
  'yemen': { ar: 'اليمن', iso2: 'YE' },
  'syria': { ar: 'سوريا', iso2: 'SY' },
  'iraq': { ar: 'العراق', iso2: 'IQ' },
  'iran': { ar: 'إيران', iso2: 'IR' },
  'lebanon': { ar: 'لبنان', iso2: 'LB' },
  'jordan': { ar: 'الأردن', iso2: 'JO' },
  'kuwait': { ar: 'الكويت', iso2: 'KW' },
  'oman': { ar: 'عُمان', iso2: 'OM' },
  'qatar': { ar: 'قطر', iso2: 'QA' },
  'bahrain': { ar: 'البحرين', iso2: 'BH' },
  'saudi arabia': { ar: 'السعودية', iso2: 'SA' },
  'united arab emirates': { ar: 'الإمارات', iso2: 'AE' },
  'egypt': { ar: 'مصر', iso2: 'EG' },
  'sudan': { ar: 'السودان', iso2: 'SD' },
  'south sudan': { ar: 'جنوب السودان', iso2: 'SS' },
  'libya': { ar: 'ليبيا', iso2: 'LY' },
  'tunisia': { ar: 'تونس', iso2: 'TN' },
  'algeria': { ar: 'الجزائر', iso2: 'DZ' },
  'morocco': { ar: 'المغرب', iso2: 'MA' },
  'mauritania': { ar: 'موريتانيا', iso2: 'MR' },
  'western sahara': { ar: 'الصحراء الغربية', iso2: 'EH' },
  'somalia': { ar: 'الصومال', iso2: 'SO' },
  'djibouti': { ar: 'جيبوتي', iso2: 'DJ' },
  'palestine': { ar: 'فلسطين', iso2: 'PS' },
  'turkey': { ar: 'تركيا', iso2: 'TR' },
  'israel': { ar: 'إسرائيل', iso2: 'IL' },
  'afghanistan': { ar: 'أفغانستان', iso2: 'AF' },
  'pakistan': { ar: 'باكستان', iso2: 'PK' },
  'india': { ar: 'الهند', iso2: 'IN' },
  'bangladesh': { ar: 'بنغلاديش', iso2: 'BD' },
  'nepal': { ar: 'نيبال', iso2: 'NP' },
  'sri lanka': { ar: 'سريلانكا', iso2: 'LK' },
  'china': { ar: 'الصين', iso2: 'CN' },
  'taiwan': { ar: 'تايوان', iso2: 'TW' },
  'japan': { ar: 'اليابان', iso2: 'JP' },
  'south korea': { ar: 'كوريا الجنوبية', iso2: 'KR' },
  'north korea': { ar: 'كوريا الشمالية', iso2: 'KP' },
  'mongolia': { ar: 'منغوليا', iso2: 'MN' },
  'kazakhstan': { ar: 'كازاخستان', iso2: 'KZ' },
  'kyrgyzstan': { ar: 'قيرغيزستان', iso2: 'KG' },
  'tajikistan': { ar: 'طاجيكستان', iso2: 'TJ' },
  'turkmenistan': { ar: 'تركمانستان', iso2: 'TM' },
  'uzbekistan': { ar: 'أوزبكستان', iso2: 'UZ' },
  'armenia': { ar: 'أرمينيا', iso2: 'AM' },
  'azerbaijan': { ar: 'أذربيجان', iso2: 'AZ' },
  'georgia': { ar: 'جورجيا', iso2: 'GE' },
  'indonesia': { ar: 'إندونيسيا', iso2: 'ID' },
  'malaysia': { ar: 'ماليزيا', iso2: 'MY' },
  'philippines': { ar: 'الفلبين', iso2: 'PH' },
  'vietnam': { ar: 'فيتنام', iso2: 'VN' },
  'thailand': { ar: 'تايلاند', iso2: 'TH' },
  'myanmar': { ar: 'ميانمار', iso2: 'MM' },
  'cambodia': { ar: 'كمبوديا', iso2: 'KH' },
  'laos': { ar: 'لاوس', iso2: 'LA' },
  'brunei': { ar: 'بروناي', iso2: 'BN' },
  'singapore': { ar: 'سنغافورة', iso2: 'SG' },
  'timor-leste': { ar: 'تيمور الشرقية', iso2: 'TL' },
  'papua new guinea': { ar: 'بابوا غينيا الجديدة', iso2: 'PG' },
  'fiji': { ar: 'فيجي', iso2: 'FJ' },
  'tonga': { ar: 'تونغا', iso2: 'TO' },
  'vanuatu': { ar: 'فانواتو', iso2: 'VU' },
  'solomon islands': { ar: 'جزر سليمان', iso2: 'SB' },
  'new zealand': { ar: 'نيوزيلندا', iso2: 'NZ' },
  'australia': { ar: 'أستراليا', iso2: 'AU' },
  'united kingdom': { ar: 'المملكة المتحدة', iso2: 'GB' },
  'ireland': { ar: 'أيرلندا', iso2: 'IE' },
  'france': { ar: 'فرنسا', iso2: 'FR' },
  'germany': { ar: 'ألمانيا', iso2: 'DE' },
  'italy': { ar: 'إيطاليا', iso2: 'IT' },
  'spain': { ar: 'إسبانيا', iso2: 'ES' },
  'portugal': { ar: 'البرتغال', iso2: 'PT' },
  'belgium': { ar: 'بلجيكا', iso2: 'BE' },
  'netherlands': { ar: 'هولندا', iso2: 'NL' },
  'switzerland': { ar: 'سويسرا', iso2: 'CH' },
  'austria': { ar: 'النمسا', iso2: 'AT' },
  'denmark': { ar: 'الدنمارك', iso2: 'DK' },
  'sweden': { ar: 'السويد', iso2: 'SE' },
  'norway': { ar: 'النرويج', iso2: 'NO' },
  'finland': { ar: 'فنلندا', iso2: 'FI' },
  'iceland': { ar: 'آيسلندا', iso2: 'IS' },
  'poland': { ar: 'بولندا', iso2: 'PL' },
  'czech republic': { ar: 'التشيك', iso2: 'CZ' },
  'slovakia': { ar: 'سلوفاكيا', iso2: 'SK' },
  'hungary': { ar: 'المجر', iso2: 'HU' },
  'romania': { ar: 'رومانيا', iso2: 'RO' },
  'bulgaria': { ar: 'بلغاريا', iso2: 'BG' },
  'greece': { ar: 'اليونان', iso2: 'GR' },
  'cyprus': { ar: 'قبرص', iso2: 'CY' },
  'malta': { ar: 'مالطا', iso2: 'MT' },
  'albania': { ar: 'ألبانيا', iso2: 'AL' },
  'serbia': { ar: 'صربيا', iso2: 'RS' },
  'croatia': { ar: 'كرواتيا', iso2: 'HR' },
  'bosnia and herzegovina': { ar: 'البوسنة والهرسك', iso2: 'BA' },
  'montenegro': { ar: 'الجبل الأسود', iso2: 'ME' },
  'north macedonia': { ar: 'مقدونيا الشمالية', iso2: 'MK' },
  'kosovo': { ar: 'كوسوفو', iso2: 'XK' },
  'moldova': { ar: 'مولدوفا', iso2: 'MD' },
  'belarus': { ar: 'بيلاروسيا', iso2: 'BY' },
  'ukraine': { ar: 'أوكرانيا', iso2: 'UA' },
  'russia': { ar: 'روسيا', iso2: 'RU' },
  'united states': { ar: 'الولايات المتحدة', iso2: 'US' },
  'canada': { ar: 'كندا', iso2: 'CA' },
  'mexico': { ar: 'المكسيك', iso2: 'MX' },
  'guatemala': { ar: 'غواتيمالا', iso2: 'GT' },
  'honduras': { ar: 'هندوراس', iso2: 'HN' },
  'el salvador': { ar: 'السلفادور', iso2: 'SV' },
  'nicaragua': { ar: 'نيكاراغوا', iso2: 'NI' },
  'costa rica': { ar: 'كوستاريكا', iso2: 'CR' },
  'panama': { ar: 'بنما', iso2: 'PA' },
  'belize': { ar: 'بليز', iso2: 'BZ' },
  'haiti': { ar: 'هايتي', iso2: 'HT' },
  'cuba': { ar: 'كوبا', iso2: 'CU' },
  'jamaica': { ar: 'جامايكا', iso2: 'JM' },
  'trinidad and tobago': { ar: 'ترينيداد وتوباغو', iso2: 'TT' },
  'bahamas': { ar: 'باهاماس', iso2: 'BS' },
  'dominican republic': { ar: 'الدومينيكان', iso2: 'DO' },
  'colombia': { ar: 'كولومبيا', iso2: 'CO' },
  'venezuela': { ar: 'فنزويلا', iso2: 'VE' },
  'guyana': { ar: 'غيانا', iso2: 'GY' },
  'suriname': { ar: 'سورينام', iso2: 'SR' },
  'ecuador': { ar: 'الإكوادور', iso2: 'EC' },
  'peru': { ar: 'بيرو', iso2: 'PE' },
  'bolivia': { ar: 'بوليفيا', iso2: 'BO' },
  'chile': { ar: 'تشيلي', iso2: 'CL' },
  'argentina': { ar: 'الأرجنتين', iso2: 'AR' },
  'brazil': { ar: 'البرازيل', iso2: 'BR' },
  'paraguay': { ar: 'باراغواي', iso2: 'PY' },
  'uruguay': { ar: 'الأوروغواي', iso2: 'UY' },
  'nigeria': { ar: 'نيجيريا', iso2: 'NG' },
  'ghana': { ar: 'غانا', iso2: 'GH' },
  'senegal': { ar: 'السنغال', iso2: 'SN' },
  'guinea': { ar: 'غينيا', iso2: 'GN' },
  'guinea-bissau': { ar: 'غينيا بيساو', iso2: 'GW' },
  'sierra leone': { ar: 'سيراليون', iso2: 'SL' },
  'liberia': { ar: 'ليبيريا', iso2: 'LR' },
  'ivory coast': { ar: 'ساحل العاج', iso2: 'CI' },
  'gambia': { ar: 'غامبيا', iso2: 'GM' },
  'benin': { ar: 'بنين', iso2: 'BJ' },
  'togo': { ar: 'توغو', iso2: 'TG' },
  'gabon': { ar: 'الغابون', iso2: 'GA' },
  'republic of congo': { ar: 'الكونغو برازافيل', iso2: 'CG' },
  'equatorial guinea': { ar: 'غينيا الاستوائية', iso2: 'GQ' },
  'cameroon': { ar: 'الكاميرون', iso2: 'CM' },
  'mali': { ar: 'مالي', iso2: 'ML' },
  'niger': { ar: 'النيجر', iso2: 'NE' },
  'burkina faso': { ar: 'بوركينا فاسو', iso2: 'BF' },
  'chad': { ar: 'تشاد', iso2: 'TD' },
  'ethiopia': { ar: 'إثيوبيا', iso2: 'ET' },
  'eritrea': { ar: 'إريتريا', iso2: 'ER' },
  'democratic republic of congo': { ar: 'الكونغو الديمقراطية', iso2: 'CD' },
  'central african republic': { ar: 'أفريقيا الوسطى', iso2: 'CF' },
  'uganda': { ar: 'أوغندا', iso2: 'UG' },
  'kenya': { ar: 'كينيا', iso2: 'KE' },
  'rwanda': { ar: 'رواندا', iso2: 'RW' },
  'burundi': { ar: 'بوروندي', iso2: 'BI' },
  'tanzania': { ar: 'تنزانيا', iso2: 'TZ' },
  'angola': { ar: 'أنغولا', iso2: 'AO' },
  'zambia': { ar: 'زامبيا', iso2: 'ZM' },
  'malawi': { ar: 'مالاوي', iso2: 'MW' },
  'mozambique': { ar: 'موزمبيق', iso2: 'MZ' },
  'zimbabwe': { ar: 'زيمبابوي', iso2: 'ZW' },
  'namibia': { ar: 'ناميبيا', iso2: 'NA' },
  'botswana': { ar: 'بوتسوانا', iso2: 'BW' },
  'eswatini': { ar: 'إسواتيني', iso2: 'SZ' },
  'lesotho': { ar: 'ليسوتو', iso2: 'LS' },
  'south africa': { ar: 'جنوب أفريقيا', iso2: 'ZA' },
  'madagascar': { ar: 'مدغشقر', iso2: 'MG' },
  'comoros': { ar: 'جزر القمر', iso2: 'KM' },
};

// Alternate English spellings/names ACLED (or other sources) may use, mapped
// to the canonical key above.
const ALIASES = {
  'uae': 'united arab emirates',
  'usa': 'united states',
  'united states of america': 'united states',
  'burma': 'myanmar',
  'dr congo': 'democratic republic of congo',
  'drc': 'democratic republic of congo',
  'congo-kinshasa': 'democratic republic of congo',
  'democratic republic of the congo': 'democratic republic of congo',
  'congo-brazzaville': 'republic of congo',
  'congo': 'republic of congo',
  "cote d'ivoire": 'ivory coast',
  'côte d’ivoire': 'ivory coast',
  'swaziland': 'eswatini',
  'czechia': 'czech republic',
  'east timor': 'timor-leste',
  'macedonia': 'north macedonia',
};

// Resolve an ACLED (or similar) English country name to { ar, iso2 }, or null
// when unmapped — callers must fall back to the raw name, never invent one.
export function resolveCountry(name) {
  if (!name) return null;
  const key = String(name).toLowerCase().trim();
  if (COUNTRY_INFO[key]) return COUNTRY_INFO[key];
  const aliased = ALIASES[key];
  if (aliased && COUNTRY_INFO[aliased]) return COUNTRY_INFO[aliased];
  return null;
}

// Every known country as { en, ar, iso2 } — `en` is the lowercase matching
// key (used to look up advisory/ACLED/GDELT records by name, never displayed
// directly). Lets securityCore.mjs iterate "every country we can label",
// rather than depending on any single source's own country list.
export function countryEntries() {
  return Object.entries(COUNTRY_INFO).map(([en, info]) => ({ en, ar: info.ar, iso2: info.iso2 }));
}
